server:
  port: 8088
#file: noinspection SpringBootApplicationYaml
spring:
  datasource:
    # noinspection SpringBootApplicationYaml
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123

#  data:
#    redis:
#      host: 127.0.0.1
#      port: 3306
#      password: 123456
#      timeout: 3000
#      database: 0
#      lettuce:
#        pool:
#          min-idle: 1
#          max-idle: 6
#          max-active: 10
#          max-wait: 1000
#        shutdown-timeout: 200